/**
 * Starter prompts for the fresh-session empty state (ChatThread). A large,
 * curated pool of **Pokémon Champions** questions (battle, Dex, rules, meta)
 * so that, across repeated visits, a user discovers the coach's range —
 * team building, Stat Points, Mega Evolution, type matchups, damage math,
 * roster lookups, and live usage (CF-CHAT-AC-1.3, CF-UI-AC-3.2).
 *
 * Every prompt is a valid Champions question. None mention other generations,
 * Mystery Dungeon, glitches, catch locations, Tera, or Smogon OU.
 *
 * This file is the **only authored pool**. iOS and Android copies are generated:
 *
 *   cd web && npm run sync:starters
 *
 * Empty chat samples one prompt per category (Battle → Dex → Rules → Meta) on
 * the client. Do not fetch this list from an API; the desk must stay instant
 * and offline. `Math.random()` belongs in `pickFiledStarters` only — never at
 * render time (hydration).
 *
 * The "Teams" chips double as discoverability for referring to a saved team by
 * name in chat ("how's my rain team?"): a build chip always produces a team, and
 * "how does my team look?" leads Oak to read the user's saved teams (or, with
 * none / for a guest, offer to build one) — an on-scope reply, never a decline.
 */

/** Filed-starter categories — fixed labels, sync across web/iOS/Android. */
export const STARTER_CATEGORIES = ["Battle", "Dex", "Rules", "Meta"] as const;

export type StarterCategory = (typeof STARTER_CATEGORIES)[number];

/**
 * One filed starter: category stamp + type-dot token + prompt text.
 * `type` is a Pokémon type token matching a `--type-*` CSS variable.
 */
export interface StarterPrompt {
  category: StarterCategory;
  /** Type token for the type-dot (e.g. `"dragon"`). */
  type: string;
  text: string;
}

export const STARTER_ENTRIES: StarterPrompt[] = [
  // Battle — competitive / nature / damage / Stat Points
  { category: "Battle", type: "dragon", text: "What's Garchomp's best nature for Speed?" },
  { category: "Battle", type: "fighting", text: "Can Garchomp OHKO Gholdengo with Earthquake?" },
  { category: "Battle", type: "fire", text: "Garchomp's Speed at level 50 with max Speed and Jolly" },
  { category: "Battle", type: "water", text: "Build me a rain team" },
  { category: "Battle", type: "psychic", text: "Build me a Trick Room team" },
  { category: "Battle", type: "fighting", text: "How does my team look?" },
  { category: "Battle", type: "water", text: "Build me a Champions team around Mega Swampert" },
  { category: "Battle", type: "dark", text: "Best Stat Point spread for Incineroar in Champions" },
  { category: "Battle", type: "fire", text: "Damage from a 120 BP STAB super-effective hit vs 95 Defense" },
  { category: "Battle", type: "water", text: "How much HP does a fully invested Blissey have?" },
  { category: "Battle", type: "dragon", text: "What's strong against Dragapult?" },
  { category: "Battle", type: "fairy", text: "Best counters to Fairy types" },
  { category: "Battle", type: "water", text: "What beats Water types?" },
  { category: "Battle", type: "steel", text: "What is Gholdengo weak to?" },
  { category: "Battle", type: "dragon", text: "Can Dragapult outspeed Flutter Mane with a Choice Scarf?" },
  { category: "Battle", type: "dark", text: "What's the best nature for Kingambit?" },
  { category: "Battle", type: "ground", text: "Does Choice Band Garchomp OHKO Toxapex with Earthquake?" },
  { category: "Battle", type: "fire", text: "Build me a sun team" },
  { category: "Battle", type: "ground", text: "Build me a sand team" },
  { category: "Battle", type: "ice", text: "Build me a snow team" },
  { category: "Battle", type: "normal", text: "How do I build a team from the Pokémon I own?" },
  { category: "Battle", type: "fairy", text: "Best Stat Point spread for Flutter Mane in Champions" },
  { category: "Battle", type: "dragon", text: "Best Stat Point spread for Dragonite in Champions" },
  { category: "Battle", type: "dragon", text: "How much Speed does Jolly Dragapult have at level 50?" },
  { category: "Battle", type: "poison", text: "What's a bulky HP investment for Toxapex?" },
  { category: "Battle", type: "fire", text: "Can Heatran live a Close Combat from Great Tusk?" },
  { category: "Battle", type: "fighting", text: "What nature should I run on Iron Hands?" },
  { category: "Battle", type: "dark", text: "Build me a hyper offense team" },
  { category: "Battle", type: "steel", text: "Build me a bulky offense team" },
  { category: "Battle", type: "water", text: "Build me a team around Pelipper" },
  { category: "Battle", type: "fire", text: "Build me a team around Torkoal" },
  { category: "Battle", type: "water", text: "How does my rain team look?" },
  { category: "Battle", type: "dark", text: "What beats Kingambit?" },
  { category: "Battle", type: "fairy", text: "What's strong against Flutter Mane?" },
  { category: "Battle", type: "ground", text: "Best counters to Great Tusk" },
  { category: "Battle", type: "water", text: "Can Rapid Strike Urshifu OHKO Incineroar?" },
  { category: "Battle", type: "steel", text: "Does Gholdengo outspeed Amoonguss?" },
  { category: "Battle", type: "rock", text: "How much damage does Salt Cure do to Steel types?" },
  { category: "Battle", type: "dragon", text: "Can a +1 Dragonite Extreme Speed OHKO Flutter Mane?" },
  { category: "Battle", type: "dark", text: "What's the Speed tier for Timid Chi-Yu?" },
  { category: "Battle", type: "fire", text: "Should I run Jolly or Adamant on Mega Charizard X?" },
  { category: "Battle", type: "fighting", text: "Build me a Champions team around Mega Lucario" },
  { category: "Battle", type: "grass", text: "Best Stat Point spread for Rillaboom in Champions" },
  { category: "Battle", type: "electric", text: "Can Pikachu OHKO a 4x weak target with Thunderbolt?" },
  { category: "Battle", type: "poison", text: "What's the best nature for Galarian Slowking?" },
  { category: "Battle", type: "grass", text: "How much HP does Ferrothorn have with max HP Stat Points?" },
  { category: "Battle", type: "flying", text: "Does Tailwind let my team outspeed Dragapult?" },
  { category: "Battle", type: "psychic", text: "Can Trick Room let Amoonguss move before Flutter Mane?" },
  { category: "Battle", type: "ice", text: "What beats Ice types in Champions?" },
  { category: "Battle", type: "dark", text: "Best counters to Dark types" },
  { category: "Battle", type: "bug", text: "Does Technician Scizor outdamage Choice Band?" },
  { category: "Battle", type: "water", text: "How much Attack does Huge Power Azumarill have?" },
  { category: "Battle", type: "psychic", text: "Build me a doubles team around Indeedee" },
  { category: "Battle", type: "ghost", text: "Should I Mega evolve Gengar or keep it base?" },

  // Dex — species / typing / learnsets on the Champions roster
  { category: "Dex", type: "ground", text: "Which Pokémon are immune to Ground?" },
  { category: "Dex", type: "dragon", text: "Show me Garchomp" },
  { category: "Dex", type: "dragon", text: "What are Dragapult's abilities?" },
  { category: "Dex", type: "fighting", text: "Tell me about Iron Valiant" },
  { category: "Dex", type: "steel", text: "Gholdengo's stats and typing" },
  { category: "Dex", type: "normal", text: "How does Eevee evolve?" },
  { category: "Dex", type: "normal", text: "What forms does Tauros have?" },
  { category: "Dex", type: "grass", text: "How do I evolve Applin?" },
  { category: "Dex", type: "flying", text: "Is Ground super effective against Flying?" },
  { category: "Dex", type: "ghost", text: "Pokémon that learn Trick Room and Will-O-Wisp" },
  { category: "Dex", type: "ground", text: "What can learn Spikes?" },
  { category: "Dex", type: "rock", text: "Who gets both Stealth Rock and Recover?" },
  { category: "Dex", type: "dark", text: "Pokémon that learn Knock Off and Roost" },
  { category: "Dex", type: "fire", text: "Fastest Fire types" },
  { category: "Dex", type: "fire", text: "Fire types that learn Will-O-Wisp with Flash Fire" },
  { category: "Dex", type: "dragon", text: "Dragon types with base Speed over 100" },
  { category: "Dex", type: "water", text: "Bulkiest Water types" },
  { category: "Dex", type: "steel", text: "Steel types that can set Stealth Rock" },
  { category: "Dex", type: "electric", text: "Fastest Pokémon in the game" },
  { category: "Dex", type: "normal", text: "Highest base stat total" },
  { category: "Dex", type: "fighting", text: "Pokémon with base Attack over 130" },
  { category: "Dex", type: "ghost", text: "How do I evolve Gimmighoul?" },
  { category: "Dex", type: "electric", text: "What's the average base Speed of Electric types?" },
  { category: "Dex", type: "normal", text: "Which type combination has the most Pokémon?" },
  { category: "Dex", type: "poison", text: "How many Pokémon are purple?" },
  { category: "Dex", type: "electric", text: "What are Rotom's forms and their types?" },
  { category: "Dex", type: "bug", text: "How does Wurmple evolve?" },
  { category: "Dex", type: "electric", text: "How do I evolve Pawmo?" },
  { category: "Dex", type: "dark", text: "What's Kingambit's typing?" },
  { category: "Dex", type: "ground", text: "Tell me about Great Tusk" },
  { category: "Dex", type: "water", text: "Combined weight of Wailord and Skitty" },
  { category: "Dex", type: "normal", text: "Which Pokémon go from dual type to monotype on evolution?" },
  { category: "Dex", type: "normal", text: "Which Pokémon have a higher catch rate than their pre-evolution?" },
  { category: "Dex", type: "normal", text: "Which Pokémon are based on cats?" },
  { category: "Dex", type: "electric", text: "How many signature moves does Pikachu have?" },
  { category: "Dex", type: "ice", text: "Is there a Fire/Ice type combination?" },
  { category: "Dex", type: "normal", text: "How many unique type combinations are missing?" },
  { category: "Dex", type: "electric", text: "Fastest Electric types" },
  { category: "Dex", type: "water", text: "Heaviest Pokémon" },
  { category: "Dex", type: "steel", text: "Lightest Pokémon" },
  { category: "Dex", type: "normal", text: "Highest base HP" },
  { category: "Dex", type: "electric", text: "Who learns both U-turn and Volt Switch?" },
  { category: "Dex", type: "flying", text: "What can learn Defog?" },
  { category: "Dex", type: "steel", text: "Steel types that learn Recover" },
  { category: "Dex", type: "ghost", text: "Ghost types with Levitate" },
  { category: "Dex", type: "bug", text: "Bug types with base Attack over 120" },
  { category: "Dex", type: "ice", text: "Ice types that can set Aurora Veil" },
  { category: "Dex", type: "fairy", text: "Fairy types with Magic Bounce" },
  { category: "Dex", type: "fighting", text: "What's the average base Attack of Fighting types?" },
  { category: "Dex", type: "dragon", text: "Dragon types immune to Electric" },
  { category: "Dex", type: "dark", text: "Who gets both Rapid Spin and Knock Off?" },
  { category: "Dex", type: "water", text: "Tell me about Walking Wake" },
  { category: "Dex", type: "grass", text: "What types does Ogerpon have?" },
  { category: "Dex", type: "psychic", text: "How does Ralts evolve?" },
  { category: "Dex", type: "rock", text: "Show me Tyranitar" },
  { category: "Dex", type: "grass", text: "Show me Rillaboom" },
  { category: "Dex", type: "dark", text: "Tell me about Incineroar" },
  { category: "Dex", type: "fairy", text: "What are Flutter Mane's stats?" },
  { category: "Dex", type: "fighting", text: "What types does Urshifu have?" },

  // Rules — Champions mechanics / abilities / items / format
  { category: "Rules", type: "ghost", text: "Does Prankster work on Dark types?" },
  { category: "Rules", type: "normal", text: "Does Fake Out work on Farigiraf?" },
  { category: "Rules", type: "ground", text: "Does Earthquake hit everyone in doubles?" },
  { category: "Rules", type: "normal", text: "How does Fake Out's priority work?" },
  { category: "Rules", type: "normal", text: "What does Leftovers do?" },
  { category: "Rules", type: "psychic", text: "What does Armor Tail do?" },
  { category: "Rules", type: "grass", text: "What does Protosynthesis do?" },
  { category: "Rules", type: "electric", text: "Can Levitate dodge Earthquake?" },
  { category: "Rules", type: "dragon", text: "Is Dragapult legal in Champions?" },
  { category: "Rules", type: "normal", text: "How does the Physical/Special split work?" },
  { category: "Rules", type: "dark", text: "How does Intimidate work in doubles?" },
  { category: "Rules", type: "ground", text: "Does Mold Breaker ignore Levitate?" },
  { category: "Rules", type: "steel", text: "What does Good as Gold do?" },
  { category: "Rules", type: "dark", text: "How does Supreme Overlord work?" },
  { category: "Rules", type: "electric", text: "What does Booster Energy do?" },
  { category: "Rules", type: "psychic", text: "Does Magic Bounce reflect Stealth Rock?" },
  { category: "Rules", type: "bug", text: "Can Rage Powder redirect a spread move?" },
  { category: "Rules", type: "psychic", text: "How does Psychic Terrain stop priority?" },
  { category: "Rules", type: "normal", text: "What does Choice Scarf do?" },
  { category: "Rules", type: "rock", text: "How does Salt Cure's residual damage work?" },
  { category: "Rules", type: "poison", text: "Does Sheer Force remove Life Orb recoil?" },
  { category: "Rules", type: "poison", text: "How does Neutralizing Gas work?" },
  { category: "Rules", type: "water", text: "Can Unaware ignore Calm Mind boosts?" },
  { category: "Rules", type: "rock", text: "What does Loaded Dice do?" },
  { category: "Rules", type: "normal", text: "How does Parental Bond work?" },
  { category: "Rules", type: "fire", text: "Does Flash Fire absorb Will-O-Wisp?" },
  { category: "Rules", type: "fire", text: "Are Mega Evolutions legal in Champions?" },
  { category: "Rules", type: "fairy", text: "Is Zacian legal in Champions?" },
  { category: "Rules", type: "dragon", text: "Is Mega Rayquaza legal in Champions?" },
  { category: "Rules", type: "fighting", text: "How do Stat Points work in Champions?" },
  { category: "Rules", type: "fighting", text: "What's the Stat Point budget in Champions?" },
  { category: "Rules", type: "fighting", text: "Can I put 32 Stat Points into one stat?" },
  { category: "Rules", type: "normal", text: "Does Champions use Stat Points instead of EVs?" },
  { category: "Rules", type: "normal", text: "How does level 50 stat calculation work?" },
  { category: "Rules", type: "dragon", text: "How do restricted Pokémon work in Champions?" },
  { category: "Rules", type: "dragon", text: "How many restricted Pokémon can I bring?" },
  { category: "Rules", type: "normal", text: "What's the team size in Champions Doubles?" },
  { category: "Rules", type: "normal", text: "Can I bring six and pick four in Champions?" },
  { category: "Rules", type: "normal", text: "How does species clause work in Champions?" },
  { category: "Rules", type: "steel", text: "Can two Pokémon hold the same item in Champions?" },
  { category: "Rules", type: "fire", text: "How does Mega Evolution work in Champions?" },
  { category: "Rules", type: "fire", text: "Can a Mega share a team with its base form?" },
  { category: "Rules", type: "normal", text: "Are Z-Moves legal in Champions?" },
  { category: "Rules", type: "flying", text: "How does Tailwind work in doubles?" },
  { category: "Rules", type: "ground", text: "Does Wide Guard block Earthquake?" },
  { category: "Rules", type: "normal", text: "Can Follow Me redirect a spread move?" },
  { category: "Rules", type: "normal", text: "Does Protect fail on consecutive uses?" },
  { category: "Rules", type: "psychic", text: "Can Prankster Tailwind go through Psychic Terrain?" },
  { category: "Rules", type: "normal", text: "How does Helping Hand work in doubles?" },
  { category: "Rules", type: "fighting", text: "What does Coaching do?" },
  { category: "Rules", type: "psychic", text: "How does Ally Switch work?" },
  { category: "Rules", type: "normal", text: "What does Assault Vest do?" },
  { category: "Rules", type: "fighting", text: "What does Choice Band do?" },
  { category: "Rules", type: "psychic", text: "What does Choice Specs do?" },
  { category: "Rules", type: "dragon", text: "What does Life Orb do?" },
  { category: "Rules", type: "normal", text: "What does Focus Sash do?" },
  { category: "Rules", type: "rock", text: "Can Sturdy survive a multi-hit move?" },
  { category: "Rules", type: "flying", text: "How does Multiscale work?" },
  { category: "Rules", type: "normal", text: "Does Unaware ignore Intimidate?" },
  { category: "Rules", type: "fairy", text: "How does Friend Guard work in doubles?" },
  { category: "Rules", type: "grass", text: "What does Safety Goggles do?" },
  { category: "Rules", type: "bug", text: "Does Overcoat block Spore?" },
  { category: "Rules", type: "water", text: "How does Storm Drain redirect Water moves?" },
  { category: "Rules", type: "electric", text: "How does Lightning Rod redirect Electric moves?" },
  { category: "Rules", type: "fighting", text: "Does Bulletproof block Aura Sphere?" },
  { category: "Rules", type: "psychic", text: "How does Magic Guard interact with Life Orb?" },
  { category: "Rules", type: "ghost", text: "What does Covert Cloak do?" },
  { category: "Rules", type: "normal", text: "How does Clear Amulet work?" },
  { category: "Rules", type: "normal", text: "Does Red Card trigger before Eject Button?" },
  { category: "Rules", type: "fighting", text: "How does Fake Out interact with Inner Focus?" },
  { category: "Rules", type: "steel", text: "What does Rocky Helmet do?" },
  { category: "Rules", type: "water", text: "How does Rough Skin work?" },
  { category: "Rules", type: "steel", text: "Does Iron Barbs stack with Rocky Helmet?" },
  { category: "Rules", type: "fire", text: "How does Flame Body's burn chance work?" },
  { category: "Rules", type: "electric", text: "What does Static do on contact?" },
  { category: "Rules", type: "poison", text: "How does Poison Touch work?" },
  { category: "Rules", type: "fighting", text: "Does Guts ignore the burn Attack drop?" },
  { category: "Rules", type: "water", text: "How does Huge Power work?" },
  { category: "Rules", type: "normal", text: "What does Simple do to stat changes?" },
  { category: "Rules", type: "water", text: "How does Contrary work?" },
  { category: "Rules", type: "fighting", text: "Does Defiant trigger on Intimidate?" },
  { category: "Rules", type: "psychic", text: "How does Competitive work?" },
  { category: "Rules", type: "steel", text: "What does Mirror Armor do?" },
  { category: "Rules", type: "normal", text: "How does Imposter work?" },
  { category: "Rules", type: "dark", text: "Can Illusion copy a Mega?" },
  { category: "Rules", type: "ghost", text: "How does Disguise work on Mimikyu?" },
  { category: "Rules", type: "flying", text: "What does Air Balloon do?" },
  { category: "Rules", type: "steel", text: "How does Heavy-Duty Boots ignore hazards?" },
  { category: "Rules", type: "psychic", text: "Does Magic Bounce reflect Taunt?" },
  { category: "Rules", type: "dark", text: "How does Taunt work in doubles?" },
  { category: "Rules", type: "normal", text: "What does Encore do?" },
  { category: "Rules", type: "normal", text: "How does Disable work?" },
  { category: "Rules", type: "electric", text: "Does Throat Spray trigger on a blocked sound move?" },
  { category: "Rules", type: "fighting", text: "How does Punching Glove work?" },
  { category: "Rules", type: "rock", text: "How does Skill Link work with Rock Blast?" },
  { category: "Rules", type: "bug", text: "Does Technician boost Ice Spinner?" },
  { category: "Rules", type: "water", text: "How does Adaptability STAB work?" },
  { category: "Rules", type: "bug", text: "What does Tinted Lens do?" },
  { category: "Rules", type: "dragon", text: "Does Sniper boost crits?" },
  { category: "Rules", type: "normal", text: "How does Super Luck work?" },
  { category: "Rules", type: "normal", text: "What does Scope Lens do?" },
  { category: "Rules", type: "fighting", text: "How does Focus Energy work?" },
  { category: "Rules", type: "poison", text: "What does Mortal Spin do?" },
  { category: "Rules", type: "water", text: "How does Court Change work?" },
  { category: "Rules", type: "poison", text: "How does Clear Smog work?" },
  { category: "Rules", type: "normal", text: "Does Roar phaze through Suction Cups?" },
  { category: "Rules", type: "normal", text: "How does Shed Tail work?" },
  { category: "Rules", type: "fairy", text: "What does Revival Blessing do?" },
  { category: "Rules", type: "psychic", text: "How does Healing Wish work?" },
  { category: "Rules", type: "psychic", text: "How does Wish timing work?" },
  { category: "Rules", type: "water", text: "What does Aqua Ring do?" },
  { category: "Rules", type: "grass", text: "Does Leech Seed fail on Grass types?" },
  { category: "Rules", type: "grass", text: "How does Strength Sap work?" },
  { category: "Rules", type: "dark", text: "What does Parting Shot do?" },
  { category: "Rules", type: "water", text: "How does Flip Turn work?" },
  { category: "Rules", type: "bug", text: "Does U-turn trigger Intimidate on the switch-in?" },
  { category: "Rules", type: "electric", text: "How does Volt Switch work in doubles?" },
  { category: "Rules", type: "normal", text: "What does Eject Pack do?" },
  { category: "Rules", type: "fighting", text: "How does Weakness Policy work?" },
  { category: "Rules", type: "grass", text: "Does White Herb clear Intimidate?" },
  { category: "Rules", type: "normal", text: "How do Stat Points interact with nature?" },
  { category: "Rules", type: "ice", text: "How does Aurora Veil work in doubles?" },
  { category: "Rules", type: "ice", text: "Does Snow Warning set snow in Champions?" },
  { category: "Rules", type: "rock", text: "How does Sand Stream work in doubles?" },
  { category: "Rules", type: "fire", text: "How does Drought work in doubles?" },
  { category: "Rules", type: "water", text: "How does Drizzle work in doubles?" },
  { category: "Rules", type: "grass", text: "How does Grassy Terrain change Grassy Glide?" },
  { category: "Rules", type: "electric", text: "Does Electric Terrain stop sleep?" },
  { category: "Rules", type: "fairy", text: "How does Misty Terrain block status?" },
  { category: "Rules", type: "ghost", text: "Are Z-Moves and Dynamax legal in Champions?" },

  // Meta — live Champions usage / roles / cores
  { category: "Meta", type: "steel", text: "What is Gholdengo's role in Champions?" },
  { category: "Meta", type: "water", text: "Who has the highest usage in Champions right now?" },
  { category: "Meta", type: "dark", text: "What's Incineroar's usage in Champions right now?" },
  { category: "Meta", type: "fire", text: "Who is the most used Mega in Champions?" },
  { category: "Meta", type: "fairy", text: "What moves is Flutter Mane running in Champions?" },
  { category: "Meta", type: "grass", text: "What's Rillaboom's role in Champions?" },
  { category: "Meta", type: "fighting", text: "How common is Urshifu in Champions?" },
  { category: "Meta", type: "dark", text: "Who partners with Incineroar in Champions?" },
  { category: "Meta", type: "ground", text: "What's Landorus's role in Champions?" },
  { category: "Meta", type: "grass", text: "What's Amoonguss's usage in Champions?" },
  { category: "Meta", type: "water", text: "Most used Water type in Champions" },
  { category: "Meta", type: "dragon", text: "What's Dragonite's role in Champions?" },
  { category: "Meta", type: "electric", text: "Who is the top restricted Pokémon in Champions?" },
  { category: "Meta", type: "fairy", text: "What item does Flutter Mane usually hold in Champions?" },
  { category: "Meta", type: "dark", text: "What's Incineroar's most common item in Champions?" },
  { category: "Meta", type: "water", text: "Who is the most used Pokémon in Champions Doubles?" },
  { category: "Meta", type: "water", text: "What's the top rain core in Champions?" },
  { category: "Meta", type: "grass", text: "Common partners for Rillaboom in Champions" },
  { category: "Meta", type: "fairy", text: "What's Flutter Mane's usual spread in Champions?" },
  { category: "Meta", type: "dark", text: "Who checks Incineroar in Champions?" },
  { category: "Meta", type: "fire", text: "What's the most used Mega stone in Champions?" },
  { category: "Meta", type: "psychic", text: "How common is Trick Room in Champions?" },
  { category: "Meta", type: "normal", text: "What's the best lead in Champions Doubles?" },
  { category: "Meta", type: "normal", text: "Who is rising in Champions usage?" },
  { category: "Meta", type: "grass", text: "What's Amoonguss usually holding in Champions?" },
  { category: "Meta", type: "fighting", text: "Common items on Urshifu in Champions" },
  { category: "Meta", type: "ground", text: "What's Landorus-Therian's usual set in Champions?" },
  { category: "Meta", type: "water", text: "Who pairs with Pelipper in Champions?" },
  { category: "Meta", type: "dragon", text: "What's the most used restricted in Champions Doubles?" },
  { category: "Meta", type: "flying", text: "How common is Tailwind in Champions?" },
  { category: "Meta", type: "dragon", text: "What's Dragonite's usual item in Champions?" },
  { category: "Meta", type: "fairy", text: "Who are the top supports in Champions?" },
  { category: "Meta", type: "steel", text: "What's Gholdengo's usual moveset in Champions?" },
  { category: "Meta", type: "normal", text: "How often is Fake Out used in Champions?" },
  { category: "Meta", type: "fire", text: "What's the top sun core in Champions?" },
  { category: "Meta", type: "fire", text: "Common partners for Torkoal in Champions" },
  { category: "Meta", type: "normal", text: "Who is the best redirection user in Champions?" },
  { category: "Meta", type: "grass", text: "What's Rillaboom's usual item in Champions?" },
  { category: "Meta", type: "normal", text: "How common is Follow Me in Champions?" },
  { category: "Meta", type: "flying", text: "What's the best speed control in Champions?" },
  { category: "Meta", type: "fairy", text: "Who is the most used Fairy in Champions?" },
  { category: "Meta", type: "dark", text: "What's Chi-Yu's role in Champions?" },
  { category: "Meta", type: "fighting", text: "How common is Iron Hands in Champions?" },
  { category: "Meta", type: "ground", text: "What's Great Tusk's usual set in Champions?" },
  { category: "Meta", type: "ground", text: "Who is the best spread attacker in Champions?" },
  { category: "Meta", type: "psychic", text: "Common partners for Indeedee in Champions" },
  { category: "Meta", type: "psychic", text: "What's the top Trick Room core in Champions?" },
  { category: "Meta", type: "dragon", text: "Who is the most used Dragon in Champions?" },
  { category: "Meta", type: "fighting", text: "What's Mega Lucario's usage in Champions?" },
  { category: "Meta", type: "fire", text: "How often is Mega Charizard X used in Champions?" },
  { category: "Meta", type: "water", text: "What's Mega Swampert's role in Champions?" },
  { category: "Meta", type: "dark", text: "Who is the best Intimidate user in Champions?" },
  { category: "Meta", type: "fighting", text: "What's the most used Fighting type in Champions?" },
  { category: "Meta", type: "dark", text: "How common is Kingambit in Champions?" },
  { category: "Meta", type: "fairy", text: "Who checks Flutter Mane in Champions?" },
  { category: "Meta", type: "steel", text: "What's the best Steel type in Champions right now?" },
  { category: "Meta", type: "fire", text: "How common is Heatran in Champions?" },
  { category: "Meta", type: "flying", text: "What's Tornadus's role in Champions?" },
  { category: "Meta", type: "ghost", text: "Who is the most used Ghost in Champions?" },
  { category: "Meta", type: "rock", text: "What's the top sand core in Champions?" },
  { category: "Meta", type: "rock", text: "How common is Tyranitar in Champions?" },
  { category: "Meta", type: "ice", text: "What's the most used Ice type in Champions?" },
  { category: "Meta", type: "flying", text: "Who is the best Tailwind setter in Champions?" },
  { category: "Meta", type: "grass", text: "What's Ogerpon's usage in Champions?" },
  { category: "Meta", type: "water", text: "How common is Walking Wake in Champions?" },
  { category: "Meta", type: "electric", text: "What's the most used Electric type in Champions?" },
  { category: "Meta", type: "psychic", text: "Who is the best terrain setter in Champions?" },
  { category: "Meta", type: "psychic", text: "What's Indeedee's role in Champions Doubles?" },
  { category: "Meta", type: "psychic", text: "How common is Psychic Terrain in Champions?" },
  { category: "Meta", type: "rock", text: "What's the best hazard setter in Champions?" },
  { category: "Meta", type: "rock", text: "Who is the most used Rock type in Champions?" },
  { category: "Meta", type: "rock", text: "What's Salt Cure's usage in Champions?" },
  { category: "Meta", type: "rock", text: "How common is Garganacl in Champions?" },
  { category: "Meta", type: "bug", text: "What's the most used Bug type in Champions?" },
  { category: "Meta", type: "water", text: "Who is the best pivot in Champions Doubles?" },
  { category: "Meta", type: "dark", text: "What's the top hyper offense core in Champions?" },
  { category: "Meta", type: "normal", text: "How common is Choice Scarf in Champions?" },
  { category: "Meta", type: "steel", text: "What's the most used item in Champions?" },
  { category: "Meta", type: "fighting", text: "Who holds the most Assault Vests in Champions?" },
  { category: "Meta", type: "ghost", text: "What's Covert Cloak usage like in Champions?" },
  { category: "Meta", type: "normal", text: "How common is Clear Amulet in Champions?" },
  { category: "Meta", type: "water", text: "What's the best rain sweeper in Champions?" },
  { category: "Meta", type: "grass", text: "How often is Grassy Terrain used in Champions?" },
  { category: "Meta", type: "grass", text: "What's the best Grassy Glide user in Champions?" },
  { category: "Meta", type: "fighting", text: "Who checks Urshifu in Champions?" },
  { category: "Meta", type: "water", text: "What's Rapid Strike Urshifu's role in Champions?" },
  { category: "Meta", type: "dark", text: "How common is Single Strike Urshifu in Champions?" },
  { category: "Meta", type: "dark", text: "What's the most used Dark type in Champions?" },
  { category: "Meta", type: "normal", text: "Who is the best Fake Out user in Champions?" },
  { category: "Meta", type: "normal", text: "How common is Wide Guard in Champions?" },
  { category: "Meta", type: "normal", text: "What's the most used Protect user in Champions?" },
  { category: "Meta", type: "fire", text: "Who is rising among Megas in Champions?" },
  { category: "Meta", type: "ghost", text: "What's Mega Gengar's usage in Champions?" },
  { category: "Meta", type: "normal", text: "How common is Mega Kangaskhan in Champions?" },
  { category: "Meta", type: "ice", text: "What's the best snow team look in Champions?" },
  { category: "Meta", type: "ice", text: "Who is the most used Ice setter in Champions?" },
  { category: "Meta", type: "ice", text: "What's Alolan Ninetales's role in Champions?" },
  { category: "Meta", type: "ice", text: "How common is Aurora Veil in Champions?" },
  { category: "Meta", type: "rock", text: "What's the best sand setter in Champions?" },
  { category: "Meta", type: "ground", text: "Who pairs with Excadrill in Champions?" },
  { category: "Meta", type: "ground", text: "What's the most used Ground type in Champions?" },
  { category: "Meta", type: "fire", text: "What's Entei's role in Champions?" },
  { category: "Meta", type: "fire", text: "Who is the most used Fire type in Champions?" },
  { category: "Meta", type: "fire", text: "What's the top sun sweeper in Champions?" },
  { category: "Meta", type: "fire", text: "How common is Drought in Champions?" },
  { category: "Meta", type: "normal", text: "What's the most used ability in Champions?" },
  { category: "Meta", type: "fairy", text: "Who is the best support Pokémon in Champions?" },
  { category: "Meta", type: "poison", text: "What's Toxapex's usage in Champions?" },
  { category: "Meta", type: "poison", text: "How common is Amoonguss over Toedscruel?" },
  { category: "Meta", type: "poison", text: "Who is the most used Poison type in Champions?" },
  { category: "Meta", type: "bug", text: "What's Scizor's role in Champions?" },
  { category: "Meta", type: "bug", text: "How common is Volcarona in Champions?" },
  { category: "Meta", type: "electric", text: "What's Miraidon's usage in Champions?" },
  { category: "Meta", type: "electric", text: "How common is Raging Bolt in Champions?" },
  { category: "Meta", type: "ghost", text: "What's Dragapult's usage in Champions Doubles?" },
  { category: "Meta", type: "steel", text: "How common is Kingambit vs Gholdengo right now?" },
];

/** Flat prompt strings — derived from {@link STARTER_ENTRIES}. */
export const STARTER_PROMPTS: string[] = STARTER_ENTRIES.map((e) => e.text);

function firstOfCategory(category: StarterCategory): StarterPrompt {
  const entry = STARTER_ENTRIES.find((e) => e.category === category);
  if (!entry) {
    throw new Error(`STARTER_ENTRIES has no ${category} prompt`);
  }
  return entry;
}

function bucket(category: StarterCategory): StarterPrompt[] {
  const entries = STARTER_ENTRIES.filter((e) => e.category === category);
  if (entries.length === 0) {
    throw new Error(`STARTER_ENTRIES has no ${category} prompt`);
  }
  return entries;
}

/**
 * Deterministic one-per-category slice (first entry of each category in file
 * order). Safe for SSR / the first client paint — no `Math.random()`.
 */
export function firstFiledStarters(): StarterPrompt[] {
  return STARTER_CATEGORIES.map(firstOfCategory);
}

/**
 * One random starter per category, in Battle → Dex → Rules → Meta order.
 * Client-side only (`Math.random()`): call from `useEffect` / `onAppear`,
 * never during render.
 */
export function pickFiledStarters(): StarterPrompt[] {
  return STARTER_CATEGORIES.map((category) => {
    const entries = bucket(category);
    return entries[Math.floor(Math.random() * entries.length)]!;
  });
}
