/**
 * build-wiki.ts — build the global `wiki_page` + `wiki_chunk` rows from the
 * gitignored Fandom crawl cache (`web/.wiki-cache/pages/*.json`).
 *
 * OFFLINE half of the wiki corpus (Oak v2 §4.2/§5); the crawl lives in
 * scripts/fetch-fandom-wiki.ts. UNLIKE the natdex snapshots, this cache is NOT
 * committed (it's multi-MB community prose, regenerated by `npm run fetch:wiki`)
 * — so in almost every environment (CI, a fresh clone, another agent's tree) the
 * cache is ABSENT. That is expected: an absent cache builds ZERO rows and logs a
 * notice; ingest never fails for a missing corpus (search_wiki then returns an
 * empty result until a crawl + re-ingest runs). GLOBAL tables — no `format`
 * column. Imported ONLY by src/ingest/run.ts, so the cache never enters the
 * Next bundle.
 *
 * `wiki_chunk.tsv` is a STORED GENERATED column — Postgres derives it from
 * section + content on insert, so the builder never sets it (it's absent from
 * the table's `$inferInsert` type).
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import type { wiki_chunk, wiki_page } from "@/data/schema";

export type WikiPageRow = typeof wiki_page.$inferInsert;
export type WikiChunkRow = typeof wiki_chunk.$inferInsert;

/** Default license for the Fandom corpus (per-page override honored if present). */
export const WIKI_LICENSE = "CC BY-SA 4.0";

const MODULE_DIR = path.dirname(fileURLToPath(import.meta.url));
/** web/.wiki-cache/pages — the crawl script writes one JSON file per page here. */
export const DEFAULT_WIKI_CACHE_DIR = path.resolve(
  MODULE_DIR,
  "..",
  "..",
  ".wiki-cache",
  "pages",
);

/** One cached section chunk, as written by the crawl script. */
interface CachedChunk {
  section: string;
  text: string;
}

/** One cached page, as written by the crawl script. */
interface CachedPage {
  /** Stable slug id (slugified title). */
  id: string;
  title: string;
  url: string;
  /** Epoch ms of the last wiki revision; null/absent if unknown. */
  revised_at?: number | null;
  /** License string; defaults to CC BY-SA 4.0 when absent. */
  license?: string;
  chunks: CachedChunk[];
}

/** The built rows for both wiki tables. */
export interface WikiRows {
  pages: WikiPageRow[];
  chunks: WikiChunkRow[];
}

function readCachedPages(cacheDir: string): CachedPage[] {
  if (!fs.existsSync(cacheDir)) {
    console.warn(
      `[wiki] cache missing at ${cacheDir} — run \`npm run fetch:wiki\`. ` +
        `Building with no wiki rows (search_wiki will return empty results).`,
    );
    return [];
  }
  const files = fs
    .readdirSync(cacheDir)
    .filter((f) => f.endsWith(".json"))
    .sort();
  const pages: CachedPage[] = [];
  for (const file of files) {
    try {
      const raw = fs.readFileSync(path.join(cacheDir, file), "utf8");
      const page = JSON.parse(raw) as CachedPage;
      if (page && page.id && page.title && page.url && Array.isArray(page.chunks)) {
        pages.push(page);
      }
    } catch {
      // Skip an unreadable/malformed page file rather than aborting the build.
      console.warn(`[wiki] skipping unreadable cache file ${file}`);
    }
  }
  return pages;
}

/**
 * Map the crawl cache → `wiki_page` + `wiki_chunk` insert rows. Chunk ids are
 * `${page.id}#${sectionIndex}` (stable + unique). Empty-text chunks are dropped.
 * Returns empty arrays when the cache is absent (never throws).
 *
 * @param cacheDir the crawl cache dir; defaults to `web/.wiki-cache/pages`.
 *   Overridable so a unit test can point at a tiny fixture dir.
 */
export function buildWikiRows(
  cacheDir: string = DEFAULT_WIKI_CACHE_DIR,
): WikiRows {
  const cached = readCachedPages(cacheDir);
  const pages: WikiPageRow[] = [];
  const chunks: WikiChunkRow[] = [];

  for (const page of cached) {
    pages.push({
      id: page.id,
      title: page.title,
      url: page.url,
      revised_at: page.revised_at ?? null,
      license: page.license ?? WIKI_LICENSE,
    });
    page.chunks.forEach((chunk, i) => {
      const section = (chunk.section ?? "").trim();
      const text = (chunk.text ?? "").trim();
      if (text.length === 0) return;
      chunks.push({
        id: `${page.id}#${i}`,
        page_id: page.id,
        section: section.length > 0 ? section : "Overview",
        content: text,
      });
    });
  }

  return { pages, chunks };
}
