package ai.gowtam.oak.features.chat

/**
 * GENERATED FILE — do not edit.
 * Source: web/src/lib/example-prompts.ts
 * Regenerate: cd web && npm run sync:starters
 *
 * Starter prompts for the fresh-thread empty state ([EmptyState]).
 * [pickFiled] returns one prompt per category (Battle → Dex → Rules → Meta).
 */
object ExamplePrompts {

    /** Filed-starter categories — fixed labels, sync across web/iOS/Android. */
    enum class Category(val label: String) {
        Battle("Battle"),
        Dex("Dex"),
        Rules("Rules"),
        Meta("Meta"),
    }

    /**
     * One filed starter: mono category label, type-dot (Pokémon type slug),
     * and the prompt text sent on tap.
     */
    data class FiledStarter(
        val category: Category,
        /** Type slug for the colored dot (e.g. `"dragon"`). */
        val typeDot: String,
        val prompt: String,
    )

    /** Canonical filed-starter pool, generated from web `STARTER_ENTRIES`. */
    val filedPool: List<FiledStarter> = listOf(
        FiledStarter(Category.Battle, "dragon", "What's Garchomp's best nature for Speed?"),
        FiledStarter(Category.Battle, "fighting", "Can Garchomp OHKO Gholdengo with Earthquake?"),
        FiledStarter(Category.Battle, "fire", "Garchomp's Speed at level 50 with max Speed and Jolly"),
        FiledStarter(Category.Battle, "water", "Build me a rain team"),
        FiledStarter(Category.Battle, "psychic", "Build me a Trick Room team"),
        FiledStarter(Category.Battle, "fighting", "How does my team look?"),
        FiledStarter(Category.Battle, "water", "Build me a Champions team around Mega Swampert"),
        FiledStarter(Category.Battle, "dark", "Best Stat Point spread for Incineroar in Champions"),
        FiledStarter(Category.Battle, "fire", "Damage from a 120 BP STAB super-effective hit vs 95 Defense"),
        FiledStarter(Category.Battle, "rock", "How much HP does Garganacl have with max HP Stat Points?"),
        FiledStarter(Category.Battle, "dragon", "What's strong against Dragapult?"),
        FiledStarter(Category.Battle, "fairy", "Best counters to Fairy types"),
        FiledStarter(Category.Battle, "water", "What beats Water types?"),
        FiledStarter(Category.Battle, "steel", "What is Gholdengo weak to?"),
        FiledStarter(Category.Battle, "dragon", "Can Dragapult outspeed Gholdengo with a Choice Scarf?"),
        FiledStarter(Category.Battle, "dark", "What's the best nature for Kingambit?"),
        FiledStarter(Category.Battle, "ground", "Does Choice Band Garchomp OHKO Toxapex with Earthquake?"),
        FiledStarter(Category.Battle, "fire", "Build me a sun team"),
        FiledStarter(Category.Battle, "ground", "Build me a sand team"),
        FiledStarter(Category.Battle, "ice", "Build me a snow team"),
        FiledStarter(Category.Battle, "normal", "How do I build a team from the Pokémon I own?"),
        FiledStarter(Category.Battle, "steel", "Best Stat Point spread for Gholdengo in Champions"),
        FiledStarter(Category.Battle, "dragon", "Best Stat Point spread for Dragonite in Champions"),
        FiledStarter(Category.Battle, "dragon", "How much Speed does Jolly Dragapult have at level 50?"),
        FiledStarter(Category.Battle, "poison", "What's a bulky HP investment for Toxapex?"),
        FiledStarter(Category.Battle, "dark", "Can Kingambit live a Close Combat from Garchomp?"),
        FiledStarter(Category.Battle, "fighting", "What nature should I run on Annihilape?"),
        FiledStarter(Category.Battle, "dark", "Build me a hyper offense team"),
        FiledStarter(Category.Battle, "steel", "Build me a bulky offense team"),
        FiledStarter(Category.Battle, "water", "Build me a team around Pelipper"),
        FiledStarter(Category.Battle, "fire", "Build me a team around Torkoal"),
        FiledStarter(Category.Battle, "water", "How does my rain team look?"),
        FiledStarter(Category.Battle, "dark", "What beats Kingambit?"),
        FiledStarter(Category.Battle, "steel", "What's strong against Gholdengo?"),
        FiledStarter(Category.Battle, "ground", "Best counters to Excadrill"),
        FiledStarter(Category.Battle, "water", "Can Palafin OHKO Incineroar?"),
        FiledStarter(Category.Battle, "steel", "Does Gholdengo outspeed Sinistcha?"),
        FiledStarter(Category.Battle, "rock", "How much damage does Salt Cure do to Steel types?"),
        FiledStarter(Category.Battle, "dragon", "Can a +1 Dragonite Extreme Speed OHKO Dragapult?"),
        FiledStarter(Category.Battle, "steel", "What's the Speed tier for Timid Gholdengo?"),
        FiledStarter(Category.Battle, "fire", "Should I run Jolly or Adamant on Mega Charizard X?"),
        FiledStarter(Category.Battle, "fighting", "Build me a Champions team around Mega Lucario"),
        FiledStarter(Category.Battle, "grass", "Best Stat Point spread for Meowscarada in Champions"),
        FiledStarter(Category.Battle, "electric", "Can Pikachu OHKO a 4x weak target with Thunderbolt?"),
        FiledStarter(Category.Battle, "poison", "What's the best nature for Galarian Slowking?"),
        FiledStarter(Category.Battle, "steel", "How much HP does Corviknight have with max HP Stat Points?"),
        FiledStarter(Category.Battle, "flying", "Does Tailwind let my team outspeed Dragapult?"),
        FiledStarter(Category.Battle, "psychic", "Can Trick Room let Hatterene move before Dragapult?"),
        FiledStarter(Category.Battle, "ice", "What beats Ice types in Champions?"),
        FiledStarter(Category.Battle, "dark", "Best counters to Dark types"),
        FiledStarter(Category.Battle, "bug", "Does Technician Scizor outdamage Choice Band?"),
        FiledStarter(Category.Battle, "water", "How much Attack does Huge Power Azumarill have?"),
        FiledStarter(Category.Battle, "psychic", "Build me a doubles team around Farigiraf"),
        FiledStarter(Category.Battle, "ghost", "Should I Mega evolve Gengar or keep it base?"),
        FiledStarter(Category.Dex, "ground", "Which Pokémon are immune to Ground?"),
        FiledStarter(Category.Dex, "dragon", "Show me Garchomp"),
        FiledStarter(Category.Dex, "dragon", "What are Dragapult's abilities?"),
        FiledStarter(Category.Dex, "fighting", "Tell me about Annihilape"),
        FiledStarter(Category.Dex, "steel", "Gholdengo's stats and typing"),
        FiledStarter(Category.Dex, "psychic", "What's Gardevoir's evolution line?"),
        FiledStarter(Category.Dex, "normal", "What forms does Tauros have?"),
        FiledStarter(Category.Dex, "grass", "What's Hydrapple's typing?"),
        FiledStarter(Category.Dex, "flying", "Is Ground super effective against Flying?"),
        FiledStarter(Category.Dex, "ghost", "Pokémon that learn Trick Room and Will-O-Wisp"),
        FiledStarter(Category.Dex, "ground", "What can learn Spikes?"),
        FiledStarter(Category.Dex, "rock", "Who gets both Stealth Rock and Recover?"),
        FiledStarter(Category.Dex, "dark", "Pokémon that learn Knock Off and Roost"),
        FiledStarter(Category.Dex, "fire", "Fastest Fire types"),
        FiledStarter(Category.Dex, "fire", "Fire types that learn Will-O-Wisp with Flash Fire"),
        FiledStarter(Category.Dex, "dragon", "Dragon types with base Speed over 100"),
        FiledStarter(Category.Dex, "water", "Bulkiest Water types"),
        FiledStarter(Category.Dex, "steel", "Steel types that can set Stealth Rock"),
        FiledStarter(Category.Dex, "electric", "Fastest Pokémon in the game"),
        FiledStarter(Category.Dex, "normal", "Highest base stat total"),
        FiledStarter(Category.Dex, "fighting", "Pokémon with base Attack over 130"),
        FiledStarter(Category.Dex, "steel", "What's Gholdengo's evolution line?"),
        FiledStarter(Category.Dex, "electric", "What's the average base Speed of Electric types?"),
        FiledStarter(Category.Dex, "normal", "Which type combination has the most Pokémon?"),
        FiledStarter(Category.Dex, "grass", "Tell me about Whimsicott"),
        FiledStarter(Category.Dex, "electric", "What are Rotom's forms and their types?"),
        FiledStarter(Category.Dex, "dragon", "What's Hydreigon's evolution line?"),
        FiledStarter(Category.Dex, "water", "What's Palafin's evolution line?"),
        FiledStarter(Category.Dex, "dark", "What's Kingambit's typing?"),
        FiledStarter(Category.Dex, "ground", "Tell me about Excadrill"),
        FiledStarter(Category.Dex, "ghost", "What's Mimikyu's typing?"),
        FiledStarter(Category.Dex, "fire", "Show me Mega Charizard X"),
        FiledStarter(Category.Dex, "psychic", "What are Farigiraf's abilities?"),
        FiledStarter(Category.Dex, "steel", "Tell me about Archaludon"),
        FiledStarter(Category.Dex, "steel", "What's Corviknight's stats?"),
        FiledStarter(Category.Dex, "ice", "Is there a Fire/Ice type combination?"),
        FiledStarter(Category.Dex, "normal", "How many unique type combinations are missing?"),
        FiledStarter(Category.Dex, "electric", "Fastest Electric types"),
        FiledStarter(Category.Dex, "fighting", "Tell me about Sneasler"),
        FiledStarter(Category.Dex, "fire", "What's Ceruledge's typing?"),
        FiledStarter(Category.Dex, "normal", "Highest base HP"),
        FiledStarter(Category.Dex, "electric", "Who learns both U-turn and Volt Switch?"),
        FiledStarter(Category.Dex, "flying", "What can learn Defog?"),
        FiledStarter(Category.Dex, "steel", "Steel types that learn Recover"),
        FiledStarter(Category.Dex, "ghost", "Ghost types with Levitate"),
        FiledStarter(Category.Dex, "bug", "Bug types with base Attack over 120"),
        FiledStarter(Category.Dex, "ice", "Ice types that can set Aurora Veil"),
        FiledStarter(Category.Dex, "fairy", "Fairy types with Magic Bounce"),
        FiledStarter(Category.Dex, "fighting", "What's the average base Attack of Fighting types?"),
        FiledStarter(Category.Dex, "dragon", "Dragon types immune to Electric"),
        FiledStarter(Category.Dex, "dark", "Who gets both Rapid Spin and Knock Off?"),
        FiledStarter(Category.Dex, "water", "Tell me about Basculegion"),
        FiledStarter(Category.Dex, "grass", "What types does Meowscarada have?"),
        FiledStarter(Category.Dex, "fighting", "What's Gallade's evolution line?"),
        FiledStarter(Category.Dex, "rock", "Show me Tyranitar"),
        FiledStarter(Category.Dex, "grass", "Show me Sinistcha"),
        FiledStarter(Category.Dex, "dark", "Tell me about Incineroar"),
        FiledStarter(Category.Dex, "dark", "What are Kingambit's stats?"),
        FiledStarter(Category.Dex, "water", "What types does Palafin have?"),
        FiledStarter(Category.Rules, "ghost", "Does Prankster work on Dark types?"),
        FiledStarter(Category.Rules, "normal", "Does Fake Out work on Farigiraf?"),
        FiledStarter(Category.Rules, "ground", "Does Earthquake hit everyone in doubles?"),
        FiledStarter(Category.Rules, "normal", "How does Fake Out's priority work?"),
        FiledStarter(Category.Rules, "normal", "What does Leftovers do?"),
        FiledStarter(Category.Rules, "psychic", "What does Armor Tail do?"),
        FiledStarter(Category.Rules, "fire", "What does Tough Claws do?"),
        FiledStarter(Category.Rules, "electric", "Can Levitate dodge Earthquake?"),
        FiledStarter(Category.Rules, "dragon", "Is Dragapult legal in Champions?"),
        FiledStarter(Category.Rules, "normal", "How does the Physical/Special split work?"),
        FiledStarter(Category.Rules, "dark", "How does Intimidate work in doubles?"),
        FiledStarter(Category.Rules, "ground", "Does Mold Breaker ignore Levitate?"),
        FiledStarter(Category.Rules, "steel", "What does Good as Gold do?"),
        FiledStarter(Category.Rules, "dark", "How does Supreme Overlord work?"),
        FiledStarter(Category.Rules, "grass", "What does Sitrus Berry do?"),
        FiledStarter(Category.Rules, "psychic", "Does Magic Bounce reflect Stealth Rock?"),
        FiledStarter(Category.Rules, "bug", "Can Rage Powder redirect a spread move?"),
        FiledStarter(Category.Rules, "psychic", "How does Psychic Terrain stop priority?"),
        FiledStarter(Category.Rules, "normal", "What does Choice Scarf do?"),
        FiledStarter(Category.Rules, "rock", "How does Salt Cure's residual damage work?"),
        FiledStarter(Category.Rules, "poison", "Does Sheer Force remove Life Orb recoil?"),
        FiledStarter(Category.Rules, "poison", "How does Neutralizing Gas work?"),
        FiledStarter(Category.Rules, "water", "Can Unaware ignore Calm Mind boosts?"),
        FiledStarter(Category.Rules, "rock", "What does Loaded Dice do?"),
        FiledStarter(Category.Rules, "normal", "How does Parental Bond work?"),
        FiledStarter(Category.Rules, "fire", "Does Flash Fire absorb Will-O-Wisp?"),
        FiledStarter(Category.Rules, "fire", "Are Mega Evolutions legal in Champions?"),
        FiledStarter(Category.Rules, "fairy", "Is Zacian legal in Champions?"),
        FiledStarter(Category.Rules, "dragon", "Is Mega Rayquaza legal in Champions?"),
        FiledStarter(Category.Rules, "fighting", "How do Stat Points work in Champions?"),
        FiledStarter(Category.Rules, "fighting", "What's the Stat Point budget in Champions?"),
        FiledStarter(Category.Rules, "fighting", "Can I put 32 Stat Points into one stat?"),
        FiledStarter(Category.Rules, "normal", "Does Champions use Stat Points instead of EVs?"),
        FiledStarter(Category.Rules, "normal", "How does level 50 stat calculation work?"),
        FiledStarter(Category.Rules, "dragon", "How do restricted Pokémon work in Champions?"),
        FiledStarter(Category.Rules, "dragon", "How many restricted Pokémon can I bring?"),
        FiledStarter(Category.Rules, "normal", "What's the team size in Champions Doubles?"),
        FiledStarter(Category.Rules, "normal", "Can I bring six and pick four in Champions?"),
        FiledStarter(Category.Rules, "normal", "How does species clause work in Champions?"),
        FiledStarter(Category.Rules, "steel", "Can two Pokémon hold the same item in Champions?"),
        FiledStarter(Category.Rules, "fire", "How does Mega Evolution work in Champions?"),
        FiledStarter(Category.Rules, "fire", "Can a Mega share a team with its base form?"),
        FiledStarter(Category.Rules, "normal", "Are Z-Moves legal in Champions?"),
        FiledStarter(Category.Rules, "flying", "How does Tailwind work in doubles?"),
        FiledStarter(Category.Rules, "ground", "Does Wide Guard block Earthquake?"),
        FiledStarter(Category.Rules, "normal", "Can Follow Me redirect a spread move?"),
        FiledStarter(Category.Rules, "normal", "Does Protect fail on consecutive uses?"),
        FiledStarter(Category.Rules, "psychic", "Can Prankster Tailwind go through Psychic Terrain?"),
        FiledStarter(Category.Rules, "normal", "How does Helping Hand work in doubles?"),
        FiledStarter(Category.Rules, "fighting", "What does Coaching do?"),
        FiledStarter(Category.Rules, "psychic", "How does Ally Switch work?"),
        FiledStarter(Category.Rules, "normal", "What does Assault Vest do?"),
        FiledStarter(Category.Rules, "fighting", "What does Choice Band do?"),
        FiledStarter(Category.Rules, "psychic", "What does Choice Specs do?"),
        FiledStarter(Category.Rules, "dragon", "What does Life Orb do?"),
        FiledStarter(Category.Rules, "normal", "What does Focus Sash do?"),
        FiledStarter(Category.Rules, "rock", "Can Sturdy survive a multi-hit move?"),
        FiledStarter(Category.Rules, "flying", "How does Multiscale work?"),
        FiledStarter(Category.Rules, "normal", "Does Unaware ignore Intimidate?"),
        FiledStarter(Category.Rules, "fairy", "How does Friend Guard work in doubles?"),
        FiledStarter(Category.Rules, "grass", "What does Safety Goggles do?"),
        FiledStarter(Category.Rules, "bug", "Does Overcoat block Spore?"),
        FiledStarter(Category.Rules, "water", "How does Storm Drain redirect Water moves?"),
        FiledStarter(Category.Rules, "electric", "How does Lightning Rod redirect Electric moves?"),
        FiledStarter(Category.Rules, "fighting", "Does Bulletproof block Aura Sphere?"),
        FiledStarter(Category.Rules, "psychic", "How does Magic Guard interact with Life Orb?"),
        FiledStarter(Category.Rules, "ghost", "What does Covert Cloak do?"),
        FiledStarter(Category.Rules, "normal", "How does Clear Amulet work?"),
        FiledStarter(Category.Rules, "normal", "Does Red Card trigger before Eject Button?"),
        FiledStarter(Category.Rules, "fighting", "How does Fake Out interact with Inner Focus?"),
        FiledStarter(Category.Rules, "steel", "What does Rocky Helmet do?"),
        FiledStarter(Category.Rules, "water", "How does Rough Skin work?"),
        FiledStarter(Category.Rules, "steel", "Does Iron Barbs stack with Rocky Helmet?"),
        FiledStarter(Category.Rules, "fire", "How does Flame Body's burn chance work?"),
        FiledStarter(Category.Rules, "electric", "What does Static do on contact?"),
        FiledStarter(Category.Rules, "poison", "How does Poison Touch work?"),
        FiledStarter(Category.Rules, "fighting", "Does Guts ignore the burn Attack drop?"),
        FiledStarter(Category.Rules, "water", "How does Huge Power work?"),
        FiledStarter(Category.Rules, "normal", "What does Simple do to stat changes?"),
        FiledStarter(Category.Rules, "water", "How does Contrary work?"),
        FiledStarter(Category.Rules, "fighting", "Does Defiant trigger on Intimidate?"),
        FiledStarter(Category.Rules, "psychic", "How does Competitive work?"),
        FiledStarter(Category.Rules, "steel", "What does Mirror Armor do?"),
        FiledStarter(Category.Rules, "normal", "How does Imposter work?"),
        FiledStarter(Category.Rules, "dark", "Can Illusion copy a Mega?"),
        FiledStarter(Category.Rules, "ghost", "How does Disguise work on Mimikyu?"),
        FiledStarter(Category.Rules, "flying", "What does Air Balloon do?"),
        FiledStarter(Category.Rules, "steel", "How does Heavy-Duty Boots ignore hazards?"),
        FiledStarter(Category.Rules, "psychic", "Does Magic Bounce reflect Taunt?"),
        FiledStarter(Category.Rules, "dark", "How does Taunt work in doubles?"),
        FiledStarter(Category.Rules, "normal", "What does Encore do?"),
        FiledStarter(Category.Rules, "normal", "How does Disable work?"),
        FiledStarter(Category.Rules, "electric", "Does Throat Spray trigger on a blocked sound move?"),
        FiledStarter(Category.Rules, "fighting", "How does Punching Glove work?"),
        FiledStarter(Category.Rules, "rock", "How does Skill Link work with Rock Blast?"),
        FiledStarter(Category.Rules, "bug", "Does Technician boost Ice Spinner?"),
        FiledStarter(Category.Rules, "water", "How does Adaptability STAB work?"),
        FiledStarter(Category.Rules, "bug", "What does Tinted Lens do?"),
        FiledStarter(Category.Rules, "dragon", "Does Sniper boost crits?"),
        FiledStarter(Category.Rules, "normal", "How does Super Luck work?"),
        FiledStarter(Category.Rules, "normal", "What does Scope Lens do?"),
        FiledStarter(Category.Rules, "fighting", "How does Focus Energy work?"),
        FiledStarter(Category.Rules, "poison", "What does Mortal Spin do?"),
        FiledStarter(Category.Rules, "water", "How does Court Change work?"),
        FiledStarter(Category.Rules, "poison", "How does Clear Smog work?"),
        FiledStarter(Category.Rules, "normal", "Does Roar phaze through Suction Cups?"),
        FiledStarter(Category.Rules, "normal", "How does Shed Tail work?"),
        FiledStarter(Category.Rules, "fairy", "What does Revival Blessing do?"),
        FiledStarter(Category.Rules, "psychic", "How does Healing Wish work?"),
        FiledStarter(Category.Rules, "psychic", "How does Wish timing work?"),
        FiledStarter(Category.Rules, "water", "What does Aqua Ring do?"),
        FiledStarter(Category.Rules, "grass", "Does Leech Seed fail on Grass types?"),
        FiledStarter(Category.Rules, "grass", "How does Strength Sap work?"),
        FiledStarter(Category.Rules, "dark", "What does Parting Shot do?"),
        FiledStarter(Category.Rules, "water", "How does Flip Turn work?"),
        FiledStarter(Category.Rules, "bug", "Does U-turn trigger Intimidate on the switch-in?"),
        FiledStarter(Category.Rules, "electric", "How does Volt Switch work in doubles?"),
        FiledStarter(Category.Rules, "normal", "What does Eject Pack do?"),
        FiledStarter(Category.Rules, "fighting", "How does Weakness Policy work?"),
        FiledStarter(Category.Rules, "grass", "Does White Herb clear Intimidate?"),
        FiledStarter(Category.Rules, "normal", "How do Stat Points interact with nature?"),
        FiledStarter(Category.Rules, "ice", "How does Aurora Veil work in doubles?"),
        FiledStarter(Category.Rules, "ice", "Does Snow Warning set snow in Champions?"),
        FiledStarter(Category.Rules, "rock", "How does Sand Stream work in doubles?"),
        FiledStarter(Category.Rules, "fire", "How does Drought work in doubles?"),
        FiledStarter(Category.Rules, "water", "How does Drizzle work in doubles?"),
        FiledStarter(Category.Rules, "grass", "How does Grassy Terrain change Grassy Glide?"),
        FiledStarter(Category.Rules, "electric", "Does Electric Terrain stop sleep?"),
        FiledStarter(Category.Rules, "fairy", "How does Misty Terrain block status?"),
        FiledStarter(Category.Rules, "ghost", "Are Z-Moves and Dynamax legal in Champions?"),
        FiledStarter(Category.Meta, "steel", "What is Gholdengo's role in Champions?"),
        FiledStarter(Category.Meta, "dragon", "What's Garchomp's usage in Champions right now?"),
        FiledStarter(Category.Meta, "dark", "What's Incineroar's usage in Champions right now?"),
        FiledStarter(Category.Meta, "fire", "What's Mega Charizard X's usage in Champions?"),
        FiledStarter(Category.Meta, "dragon", "What moves is Dragapult running in Champions?"),
        FiledStarter(Category.Meta, "grass", "What's Sinistcha's role in Champions?"),
        FiledStarter(Category.Meta, "water", "How common is Palafin in Champions?"),
        FiledStarter(Category.Meta, "dark", "Who partners with Incineroar in Champions?"),
        FiledStarter(Category.Meta, "ground", "What's Excadrill's role in Champions?"),
        FiledStarter(Category.Meta, "grass", "What's Whimsicott's usage in Champions?"),
        FiledStarter(Category.Meta, "water", "What's Pelipper's usual set in Champions?"),
        FiledStarter(Category.Meta, "dragon", "What's Dragonite's role in Champions?"),
        FiledStarter(Category.Meta, "dragon", "What item does Dragapult usually hold in Champions?"),
        FiledStarter(Category.Meta, "dark", "What's Incineroar's most common item in Champions?"),
        FiledStarter(Category.Meta, "dragon", "What's Garchomp's usage in Champions Doubles?"),
        FiledStarter(Category.Meta, "grass", "Common partners for Sinistcha in Champions"),
        FiledStarter(Category.Meta, "steel", "What's Gholdengo's usual spread in Champions?"),
        FiledStarter(Category.Meta, "dark", "Who checks Incineroar in Champions?"),
        FiledStarter(Category.Meta, "water", "What's Mega Swampert's usual item in Champions?"),
        FiledStarter(Category.Meta, "psychic", "How common is Hatterene in Champions?"),
        FiledStarter(Category.Meta, "grass", "What's Whimsicott's role in Champions Doubles?"),
        FiledStarter(Category.Meta, "fighting", "What's Annihilape's usage in Champions?"),
        FiledStarter(Category.Meta, "poison", "What's Toxapex usually holding in Champions?"),
        FiledStarter(Category.Meta, "water", "Common items on Palafin in Champions"),
        FiledStarter(Category.Meta, "dragon", "What's Garchomp's usual set in Champions?"),
        FiledStarter(Category.Meta, "water", "Who pairs with Pelipper in Champions?"),
        FiledStarter(Category.Meta, "steel", "What's Archaludon's usage in Champions Doubles?"),
        FiledStarter(Category.Meta, "flying", "What's Staraptor's usual item in Champions?"),
        FiledStarter(Category.Meta, "dragon", "What's Dragonite's usual item in Champions?"),
        FiledStarter(Category.Meta, "psychic", "What's Farigiraf's role in Champions?"),
        FiledStarter(Category.Meta, "steel", "What's Gholdengo's usual moveset in Champions?"),
        FiledStarter(Category.Meta, "dark", "What's Incineroar's usual moveset in Champions?"),
        FiledStarter(Category.Meta, "fire", "What's Torkoal's usual set in Champions?"),
        FiledStarter(Category.Meta, "fire", "Common partners for Torkoal in Champions"),
        FiledStarter(Category.Meta, "fairy", "What's Clefable's role in Champions?"),
        FiledStarter(Category.Meta, "grass", "What's Meowscarada's usual item in Champions?"),
        FiledStarter(Category.Meta, "fairy", "How common is Clefable in Champions?"),
        FiledStarter(Category.Meta, "flying", "What's Whimsicott's usual moveset in Champions?"),
        FiledStarter(Category.Meta, "fairy", "What's Sylveon's usage in Champions?"),
        FiledStarter(Category.Meta, "dragon", "What's Hydreigon's role in Champions?"),
        FiledStarter(Category.Meta, "fighting", "How common is Annihilape in Champions?"),
        FiledStarter(Category.Meta, "ground", "What's Excadrill's usual set in Champions?"),
        FiledStarter(Category.Meta, "dragon", "What's Garchomp's usual moveset in Champions?"),
        FiledStarter(Category.Meta, "psychic", "Common partners for Farigiraf in Champions"),
        FiledStarter(Category.Meta, "psychic", "What's Hatterene's usual set in Champions?"),
        FiledStarter(Category.Meta, "dragon", "What's Dragapult's role in Champions?"),
        FiledStarter(Category.Meta, "fighting", "What's Mega Lucario's usage in Champions?"),
        FiledStarter(Category.Meta, "fire", "How often is Mega Charizard X used in Champions?"),
        FiledStarter(Category.Meta, "water", "What's Mega Swampert's role in Champions?"),
        FiledStarter(Category.Meta, "fire", "What's Arcanine's role in Champions?"),
        FiledStarter(Category.Meta, "fighting", "What's Annihilape's role in Champions?"),
        FiledStarter(Category.Meta, "dark", "How common is Kingambit in Champions?"),
        FiledStarter(Category.Meta, "steel", "Who checks Gholdengo in Champions?"),
        FiledStarter(Category.Meta, "steel", "What's Corviknight's role in Champions?"),
        FiledStarter(Category.Meta, "fire", "How common is Torkoal in Champions?"),
        FiledStarter(Category.Meta, "flying", "What's Staraptor's role in Champions?"),
        FiledStarter(Category.Meta, "ghost", "What's Gengar's usage in Champions?"),
        FiledStarter(Category.Meta, "rock", "Who pairs with Tyranitar in Champions?"),
        FiledStarter(Category.Meta, "rock", "How common is Tyranitar in Champions?"),
        FiledStarter(Category.Meta, "ice", "What's Alolan Ninetales's usage in Champions?"),
        FiledStarter(Category.Meta, "grass", "Does Whimsicott set Tailwind in Champions?"),
        FiledStarter(Category.Meta, "grass", "What's Meowscarada's usage in Champions?"),
        FiledStarter(Category.Meta, "water", "How common is Basculegion in Champions?"),
        FiledStarter(Category.Meta, "electric", "What's Raichu's usage in Champions?"),
        FiledStarter(Category.Meta, "psychic", "What's Hatterene's role in Champions Doubles?"),
        FiledStarter(Category.Meta, "psychic", "What's Farigiraf's usual item in Champions?"),
        FiledStarter(Category.Meta, "rock", "What's Glimmora's usage in Champions?"),
        FiledStarter(Category.Meta, "rock", "What's Garganacl's usage in Champions?"),
        FiledStarter(Category.Meta, "rock", "What's Garganacl's usual moveset in Champions?"),
        FiledStarter(Category.Meta, "rock", "How common is Garganacl in Champions?"),
        FiledStarter(Category.Meta, "bug", "What's Volcarona's usage in Champions?"),
        FiledStarter(Category.Meta, "water", "What's Pelipper's role in Champions Doubles?"),
        FiledStarter(Category.Meta, "fire", "What's Mega Charizard X's usual set in Champions?"),
        FiledStarter(Category.Meta, "dragon", "What's Garchomp's most common item in Champions?"),
        FiledStarter(Category.Meta, "poison", "What's Toxapex's usual item in Champions?"),
        FiledStarter(Category.Meta, "psychic", "Does Farigiraf run Covert Cloak in Champions?"),
        FiledStarter(Category.Meta, "dragon", "Does Garchomp run Clear Amulet in Champions?"),
        FiledStarter(Category.Meta, "water", "What's Palafin's role in rain in Champions?"),
        FiledStarter(Category.Meta, "grass", "What's Meowscarada's usual moveset in Champions?"),
        FiledStarter(Category.Meta, "water", "Who checks Palafin in Champions?"),
        FiledStarter(Category.Meta, "water", "What's Palafin's role in Champions?"),
        FiledStarter(Category.Meta, "fighting", "What's Sneasler's role in Champions?"),
        FiledStarter(Category.Meta, "dark", "What's Grimmsnarl's usage in Champions?"),
        FiledStarter(Category.Meta, "normal", "Does Incineroar run Fake Out in Champions?"),
        FiledStarter(Category.Meta, "poison", "What's Toxapex's usual moveset in Champions?"),
        FiledStarter(Category.Meta, "dragon", "What's Mega Garchomp's usage in Champions?"),
        FiledStarter(Category.Meta, "ghost", "What's Mega Gengar's usage in Champions?"),
        FiledStarter(Category.Meta, "normal", "How common is Mega Kangaskhan in Champions?"),
        FiledStarter(Category.Meta, "ice", "What's Alolan Ninetales's usual set in Champions?"),
        FiledStarter(Category.Meta, "ice", "How common is Alolan Ninetales in Champions?"),
        FiledStarter(Category.Meta, "ice", "What's Alolan Ninetales's role in Champions?"),
        FiledStarter(Category.Meta, "ice", "Does Alolan Ninetales run Aurora Veil in Champions?"),
        FiledStarter(Category.Meta, "rock", "What's Tyranitar's role in Champions?"),
        FiledStarter(Category.Meta, "ground", "Who pairs with Excadrill in Champions?"),
        FiledStarter(Category.Meta, "ground", "What's Excadrill's usage in Champions?"),
        FiledStarter(Category.Meta, "fire", "What's Arcanine's usage in Champions?"),
        FiledStarter(Category.Meta, "fire", "What's Ceruledge's usage in Champions?"),
        FiledStarter(Category.Meta, "fire", "What's Mega Charizard Y's usage in Champions?"),
        FiledStarter(Category.Meta, "grass", "What's Whimsicott's usual item in Champions?"),
        FiledStarter(Category.Meta, "poison", "What's Toxapex's usage in Champions?"),
        FiledStarter(Category.Meta, "grass", "How common is Sinistcha vs Whimsicott right now?"),
        FiledStarter(Category.Meta, "rock", "What's Glimmora's role in Champions?"),
        FiledStarter(Category.Meta, "bug", "What's Scizor's role in Champions?"),
        FiledStarter(Category.Meta, "bug", "How common is Volcarona in Champions?"),
        FiledStarter(Category.Meta, "steel", "What's Archaludon's usage in Champions?"),
        FiledStarter(Category.Meta, "electric", "How common is Raichu in Champions?"),
        FiledStarter(Category.Meta, "ghost", "What's Dragapult's usage in Champions Doubles?"),
        FiledStarter(Category.Meta, "steel", "How common is Kingambit vs Gholdengo right now?"),
    )

    /**
     * One filed starter per category (Battle → Dex → Rules → Meta), each
     * sampled at random from that category's entries in [filedPool].
     */
    fun pickFiled(): List<FiledStarter> =
        Category.entries.map { category ->
            filedPool.filter { it.category == category }.random()
        }
}
